# https://docs.microsoft.com/azure/devops/pipelines/ecosystems/xcode
pool:
# change vm to 10.15 when after this issue will be resolved
# test
#https://github.com/microsoft/azure-pipelines-image-generation/issues/1277
  vmImage: 'macOS-10.14'
  
variables:
  scheme: 'iOSPipelineTest'
  sdk: 'iphoneos'
  configuration: 'Release'

steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'BritenetDistribution.p12'
    certPwd: '$(P12password)'
    keychain: 'temp'
    signingIdentity: 'iPhone Distribution: Britenet Sp. z o.o. (772RH2549C)'

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'AzureStore.mobileprovision'
    
- task: Xcode@5
  inputs:
    sdk: '$(sdk)'
    scheme: '$(scheme)'
    configuration: '$(configuration)'
    xcodeVersion: '11'
    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
    packageApp: true
    signingOption: 'manual'
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(System.ArtifactsDirectory)'
    
