# https://docs.microsoft.com/azure/devops/pipelines/ecosystems/xcode
pool:
# change vm to 10.15 when after this issue will be resolved
# test
#https://github.com/microsoft/azure-pipelines-image-generation/issues/1277
  vmImage: 'macOS-10.14'
  
variables:
  scheme: 'iOSPipelineTest'
  sdk: 'iphoneos'
  configuration: 'Release'
  AZP_CACHING_TAR: 'true'
  AZP_CACHING_CONTENT_FORMAT: 'SingleTar'
  CACHE_RESTORED: 'false'

steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'BritenetDistribution.p12'
    certPwd: '$(P12password)'
    keychain: 'temp'
    signingIdentity: 'iPhone Distribution: Britenet Sp. z o.o. (772RH2549C)'

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'AzureStore.mobileprovision'
    
- task: CacheBeta@1
  inputs:
    key: 'carthage | $(Agent.OS) | Cartfile.resolved'
    path: '$(Pipeline.Workspace)/Carthage/Build/iOS'
    cacheHitVar: 'CACHE_RESTORED'

- script: carthage update --platform iOS 
  condition: ne(variables.CACHE_RESTORED, 'true')

- task: Xcode@5
  inputs:
    actions: 'build'
    configuration: '$(configuration)'
    sdk: '$(sdk)'
    xcWorkspacePath: 'iOSPipelineTest.xcodeproj/project.xcworkspace'
    scheme: '$(scheme)'
    xcodeVersion: 'specifyPath'
    xcodeDeveloperDir: '/Applications/Xcode_11.3.app'
    packageApp: true
    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
    signingOption: 'manual'
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(System.ArtifactsDirectory)'
    
