# https://docs.microsoft.com/azure/devops/pipelines/ecosystems/xcode
pool:
# change vm to 10.15 when after this issue will be resolved
#https://github.com/microsoft/azure-pipelines-image-generation/issues/1277
  vmImage: 'macOS-10.14'
  
variables:
  scheme: ''
  sdk: 'iphoneos'
  configuration: 'Release'

steps:
# Install Apple certificate
# Install an Apple certificate required to build on a macOS agent machine
- - task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'chrisid_iOSDev_Nov2018.p12'
    certPwd: $(P12Password)

- task: InstallAppleProvisioningProfile@1
  inputs:
    provProfileSecureFile: '6ffac825-ed27-47d0-8134-95fcf37a666c.mobileprovision'
    
- task: Xcode@5
  inputs:
    sdk: '$(sdk)'
    scheme: '$(scheme)'
    configuration: '$(configuration)'
    xcodeVersion: '11'
    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
    packageApp: false
